---
abstract: 'Get/Validate data from credit & debit cards'
author:
  - 'purge: Simon Elliott <cpan@browsing.co.uk>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CardInfo
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.51
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
